### PR TITLE
Unquote quoted keys/values

### PR DESCRIPTION
**Pull request by mthjs**
Currently `:` is seen as a delimiter for key-value pairs, eventhough it
might be used as a regular character in the value of a key-value pair.

By ignoring all special cases when the value is double-quoted, we can
reuse special characters like `:` and `,`.

### CODE REVIEW

**Comment by vmihailenco** [comment]
Why not to use single quotes? They already work.

Double quotes are already used by Go tags so they must be escaped.

**Comment by mthjs** [comment]
reference to related issue in msgpack-repo https://github.com/vmihailenco/msgpack/issues/296

**Comment by mthjs** [comment]
single quotes would be nicer indeed, but they didn't work as we expected. I assume this is due to the addition of the quotes to the parsed value. Neither `msgpack:"'device:uid'"` nor `msgpack:'device:uid'` seemed to work

**Comment by mthjs** [comment]
I've removed the quotes for msgpack locally (see result below), now it works with the tag `msgpack:"'device:uid'"`. Is there a reason for the addition of the single-quotes to the parsed value, or can I remove them safely?

```
func (p *tagParser) parseQuotedValue() {
	const quote = '\''

	var b []byte
	//b = append(b, quote)

	for p.Valid() {
		bb, ok := p.ReadSep(quote)
		if !ok {
			b = append(b, bb...)
			break
		}

		if len(bb) > 0 && bb[len(bb)-1] == '\\' {
			b = append(b, bb[:len(bb)-1]...)
			//b = append(b, quote)
			continue
		}

		b = append(b, bb...)
		//b = append(b, quote)
		break
	}

	p.setTagOption(p.key, string(b))
	if p.Skip(',') {
		p.Skip(' ')
	}
	p.parseKey()
}
```

**Comment by vmihailenco** [comment]
@mthjs this is for go-pg which uses `tagparser.Unquote` to check if the value was quoted or not. I am not sure it is a good design.

It looks like there are 2 options:
- call `tagparser.Unquote` in msgpack lib
- fix tagparser to unquote automatically and release it as tagparser v2 and use it in msgpack

**Comment by mthjs** [comment]
My personal preference goes to the second option.  From a quick glance in `go-pg` it seems `tagparser.Unquote` is always used to unquote the value, whether the value is quoted or not. This signals to me that the quotation-marks aren't particular useful besides escaping. Somewhat related, `tagparser.Unquote` seems to be a limited version of `strconv.Unquote` https://golang.org/pkg/strconv/#Unquote which is part of go's standard-library.

I'll update this pull-request. Quotes will no longer be added to the parsed value, and Unquote will be removed

**Comment by vmihailenco** [comment]
Thanks @mthjs . I will release this as v2 .

**Pull request merged**
